###
POST https://{{host}}/{{version}}/image-parameters
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
    "name": "Test Image Parameter",
    "image_id": "{{dev_image_id}}",
    "key": "Username",
    "type": "String",
    "description": "Lorem ipsum",
    "required": true,
    "validation_rule": "/\\w+/"
}

> {%

client.global.set("image_parameter_id", response.body.data.id);
client.log("Image Parameter ID: " + response.body.data.id);

client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###
GET https://{{host}}/{{version}}/image-parameters
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET https://{{host}}/{{version}}/image-parameters/{{image_parameter_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
PATCH https://{{host}}/{{version}}/image-parameters/{{image_parameter_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
    "name": "RENAMED",
    "image_id": "{{dev_image_id}}",
    "key": "RENAMED",
    "type": "Boolean",
    "description": "RENAMED",
    "required": false,
    "validation_rule": "RENAMED"
}

> {%

client.global.set("image_id", response.body.data.id);
client.log("Image ID: " + response.body.data.id);

client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET https://{{host}}/{{version}}/image-parameters/{{image_parameter_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");

  client.assert(response.body.data.name === "RENAMED");
  client.assert(response.body.data.key === "RENAMED");
  client.assert(response.body.data.type === "Boolean");
  client.assert(response.body.data.description === "RENAMED");
  client.assert(response.body.data.required === false);
  client.assert(response.body.data.validation_rule === "RENAMED");
});
%}

###
DELETE https://{{host}}/{{version}}/image-parameters/{{image_parameter_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###
GET https://{{host}}/{{version}}/image-parameters/{{image_parameter_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 404, "Response status is not 404");
});
%}