POST https://{{host}}/{{version}}/vpcs
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json
X-Reseller-Id: 1

{
  "name": "Test",
  "region_id": "reg-a63dd78c"
}

###

GET https://ecloud-apio.paul.rnd.ukfast/v2/vpcs/vpc-30a4b852
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

###


GET https://ecloud-apio.paul.rnd.ukfast/v2/dhcps/dhcp-87473679
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

###

