###
# Run these steps one by one
###
# 1. First Create a Data Centre
POST https://{{host}}/{{version}}/vpcs
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
  "name": "Manchester Data Centre 1",
  "region_id": "reg-9afb9143"
}

> {%
client.global.set('vdc_id', response.body.data.id);
client.log('Data Centre UUID: ' + response.body.data.id);
%}

###
# 2. View the data centre collection
GET https://{{host}}/{{version}}/vdcs
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

###
# 3. Get detail on the data centre we created
GET https://{{host}}/{{version}}/vdcs/{{vdc_id}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

###
# 4. Update the data centre we created
PATCH https://{{host}}/{{version}}/vdcs/{{vdc_id}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
  "name": "Manchester Region Data Centre 1"
}

###
# 5. Verify the name has changed
GET https://{{host}}/{{version}}/vdcs/{{vdc_id}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

###
# 6. Now delete the data centre
DELETE https://{{host}}/{{version}}/vdcs/{{vdc_id}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

###
# 7. And verify that the data centre is deleted
GET https://{{host}}/{{version}}/vdcs/{{vdc_id}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json