properties:
  id:
    type: string
    example: rt-2b66bb79
    readOnly: true
  name:
    type: string
    required: false
    example: 'Resource Tier 1'
    readOnly: false
  availability_zone_id:
    type: string
    required: true
    example: 'az-2b66bb79'
    readOnly : false
  created_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
  updated_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
description: 'Resource Tiers'
