properties:
  id:
    type: string
    example: vip-2b66bb79
    readOnly: true
  name:
    type: string
    required: false
    example: 'VIP 1'
    readOnly: false
  load_balancer_network_id:
    type: string
    required: true
    description : "ID of the load balancer network that the VIP is associated with."
    example: lbn-4c63cf58
    readOnly: false
  ip_address_id:
    type: string
    required: false
    description : "ID of the IP address assigned to the resource."
    example: ip-4c63cf58
    readOnly: true
  config_id:
    type: integer
    readOnly: true
    example: 12345
    description: Load balancer service VIP identification
  sync :
    type : object
    readOnly : true
    properties :
      status :
        description : "The status of the most recent sync performed on the resource. Possible values: in-progress, failed, complete."
        example : complete
      type :
        description : "The type of the most recent sync performed on the resource. Possible values: update / delete."
        example : update
  created_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
  updated_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
description: 'VIPs'
