GET https://{{host}}/{{version}}/volumes/vol-e5083b12
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 1-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json



###
GET https://{{host}}/{{version}}/volumes/vol-e5083b12
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 1-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.global.set('volume_id', response.body.data[0].id);
client.log('Volume ID: ' + response.body.data[0].id);

client.global.set('volume_capacity', response.body.data[0].capacity);
client.log('Volume Capacity: ' + response.body.data[0].capacity);
client.global.set('new_capacity', response.body.data[0].capacity+1);
client.log('New Capacity: ' + client.global.get('new_capacity'));

%}

###


# vol-43a88322 no billing

# vol-e5083b12

PATCH https://{{host}}/{{version}}/volumes/vol-e5083b12
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 1-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
  "capacity": 10
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

%}

###
