### 1. Get Instance
GET https://{{host}}/{{version}}/instances?sort=created_at:desc&per_page=1
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test('Get Instance', function () {
    client.assert(response.status === 200, '200 response not received');
});
client.global.set('instance_id', response.body.data[0].id);
client.global.set('availability_zone_id', response.body.data[0].availability_zone_id);
client.log('Instance ID: ' + response.body.data[0].id);
client.log('Availability Zone ID: ' + response.body.data[0].availability_zone_id);
%}

### 2. Get Volume from different AZ
GET https://{{host}}/{{version}}/volumes?availability_zone_id:neq={{availability_zone_id}}&sort=created_at:desc&per_page=1
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test('Get Volume from Different AZ', function () {
    client.assert(response.status === 200, '200 response not received');
});
client.global.set('volume_id', response.body.data[0].id);
client.log('Volume ID: ' + response.body.data[0].id);
%}

### 3. Attempt to attach it
POST https://{{host}}/{{version}}/instances/{{instance_id}}/volume-attach
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
    "volume_id": "{{volume_id}}"
}

> {%
client.test('Attach wrong AZ Volume to Instance', function () {
    client.assert(response.status === 422, '422 response not received');
    client.assert(
        response.body.errors[0].detail === 'The volume is not in the same availability zone as the instance',
        'Expected error detail not received'
    );
});
%}

### 4. Get Volume from Same AZ
GET https://{{host}}/{{version}}/volumes?availability_zone_id:eq={{availability_zone_id}}&sort=created_at:desc&per_page=1
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test('Get Volume from Different AZ', function () {
    client.assert(response.status === 200, '200 response not received');
});
client.global.set('volume_id', response.body.data[0].id);
client.log('Volume ID: ' + response.body.data[0].id);
%}

### 5. Attempt to attach it
POST https://{{host}}/{{version}}/instances/{{instance_id}}/volume-attach
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
    "volume_id": "{{volume_id}}"
}

> {%
client.test('Attach volume to instance', function () {
    client.assert(response.status === 202, '202 response not received');
});
%}

### 6. Detach it
POST https://{{host}}/{{version}}/instances/{{instance_id}}/volume-detach
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
    "volume_id": "{{volume_id}}"
}

> {%
client.test('Attach volume to instance', function () {
    client.assert(response.status === 202, '202 response not received');
});
%}