allOf :
  - $ref : 'public_schema.yaml'
  - type : object
    properties :
      image_id:
        type: string
        example: img-aaaaaaaa
        readOnly: false
      created_at:
        type: string
        example: '2021-09-23T10:00:00+01:00'
        readOnly: true
      updated_at:
        type: string
        example: '2021-09-23T10:00:00+01:00'
        readOnly: true

