properties:
  id:
    type: string
    example: lbs-0c03049b-dev
    readOnly: true
  name:
    type: string
    example: 'small'
    readOnly: false
  node_count:
    type: integer
    example: 1
    readOnly: false
  cpu:
    type: integer
    example: 1
    readOnly: false
  ram:
    type: integer
    example: 2
    readOnly: false
  hdd:
    type: integer
    example: 20
    readOnly: false
  iops:
    type: integer
    example: 300
    readOnly: false
  image_id:
    type: string
    example: img-aaaaaaaa
    readOnly: false
  created_at:
    type: string
    example: '2021-09-23T10:00:00+01:00'
    readOnly: true
  updated_at:
    type: string
    example: '2021-09-23T10:00:00+01:00'
    readOnly: true
description: 'Load Balancer Specifications'
