version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    image: apio-ecloud
    env_file:
      - .env
    depends_on:
      - redis
  queue:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    image: apio-ecloud
    command: queue
    env_file:
      - .env
    depends_on:
      - redis
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    image: apio-ecloud
    command: scheduler
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:latest
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/compose/ssl:/etc/nginx/ssl
      - ./.docker/compose/proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
