envFromSecrets: 
  - "elasticsearch-auth"
  - "mail-auth"
  - "apio-ecloud"
      
hostAliases:
- ip: "172.16.64.22"
  hostnames:
  - vault.ukfast.net
- ip: "94.229.162.196"
  hostnames:
  - "uk-man4-14.console.ecloud.uk"
