openapi: 3.0.0
info:
  version: 1.0.0
  title: 'UKFast NSX APIo'
servers:
  -
    url: 'https://api.ukfast.io'
security:
  -
    api_key:
      - api_key
components:
  schemas:
    VirtualDataCentres:
      properties:
        id:
          type: string
          example: 78e8a223-c125-4641-8ca9-c201d2cc4785
          generationStrategy: uuid
          readOnly: false
        name:
          type: string
          example: 'Manchester Datacentre 1'
          readOnly: false
        created_at:
          type: string
          example: '2020-07-07T10:30:00+01:00'
          readOnly: false
        updated_at:
          type: string
          example: '2020-07-07T10:30:00+01:00'
          readOnly: false
        deleted_at:
          type: string
          example: '2020-07-07T10:30:00+01:00'
          readOnly: false
      description: 'Virtual Data Centres'
      required: {  }
    securitySchemas:
      api_key:
        type: apiKey
        description: 'API Key Authentication'
        in: header
        name: Authorization
paths:
  '/ecloud/v2/vdcs':
    get:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/VirtualDataCentres'
                  meta:
                    type: object
                    required:
                      - pagination
                    properties:
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 30
                          count:
                            type: integer
                            example: 10
                          per_page:
                            type: integer
                            example: 10
                          current_page:
                            type: integer
                            example: 2
                          total_pages:
                            type: integer
                            example: 3
                          links:
                            type: object
                            properties:
                              first:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/vdcs?page=1'
                              previous:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/vdcs?page=1'
                              next:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/vdcs?page=2'
                              last:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/vdcs?page=2'
      tags:
        - VirtualDataCentres
      parameters:
        -
          name: per_page
          in: query
          required: false
          schema:
            type: integer
          description: 'Number of items to display per page'
        -
          name: page
          in: query
          required: false
          schema:
            type: integer
          description: 'Page number to jump to'

    post:
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: e61bfc11-f423-437c-bde3-68b07bb3d371
                  meta:
                    type: object
                    properties:
                      location:
                        type: string
                        example: 'https://api.ukfast.io/ecloud/v2/vdcs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VirtualDataCentres'
      tags:
        - VirtualDataCentres
      parameters: {  }
  '/ecloud/v2/vdcs/{vdcUuid}':
    get:
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/VirtualDataCentres'
                  meta:
                    type: object
      tags:
        - VirtualDataCentres
      parameters:
        -
          name: vdcUuid
          in: path
          required: true
          schema:
            type: uuid
          example: e61bfc11-f423-437c-bde3-68b07bb3d371
    patch:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id: string
                      example: e61bfc11-f423-437c-bde3-68b07bb3d371
                  meta:
                    type: object
                    properties:
                      location:
                        type: string
                        example: 'https://api.ukfast.io/ecloud/v2/availability-zones/{vdcUuid}'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VirtualDataCentres'
      tags:
        - VirtualDataCentres
      parameters:
        -
          name: vdcUuid
          in: path
          required: true
          schema:
            type: uuid
          example: e61bfc11-f423-437c-bde3-68b07bb3d371
    delete:
      responses:
        204:
          description: Success
      tags:
        - VirtualDataCentres
      parameters:
        -
          name: zoneUuid
          in: path
          required: true
          schema:
            type: uuid
          example: e61bfc11-f423-437c-bde3-68b07bb3d371