properties:
  id:
    type: string
    example: 'volgroup-2b66bb79'
    readOnly: true
  name:
    type: string
    required: false
    example: 'volgroup-2b66bb79'
  vpc_id:
    type: string
    required: true
    example: 'vpc-2b66bb79'
    readOnly: false
  availability_zone_id:
    type: string
    required: true
    example: 'az-2b66bb79'
    readOnly: false
  usage :
    type : object
    readOnly : true
    properties :
      volumes :
        type: integer
        description : "The number of volumes associated with this volume group."
        example : 10
  sync :
    type : object
    readOnly : true
    properties :
      status :
        description : "The status of the most recent sync performed on the resource. Possible values: in-progress, failed, complete."
        example : complete
      type :
        description : "The type of the most recent sync performed on the resource. Possible values: update / delete."
        example : update
  created_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
  updated_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
description: 'Vpns'
