properties:
  id:
    type: string
    example: img-2b66bb79
    readOnly: true
  name:
    type: string
    example: 'MySQL root password'
    readOnly: true
  key:
    type: string
    example: 'mysql_root_password'
    readOnly: true
  type:
    type: string
    example: 'Password'
    readOnly: true
  description:
    type: string
    example: 'The root password for the MySQL database'
    readOnly: true
  required:
    type: boolean
    example: true
    readOnly: true
  validation_rule:
    type: string
    example: '/\\w+/'
    readOnly: true
  created_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
  updated_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
description: 'Image Parameters'
