properties:
  pagination:
    type: object
    properties:
      total:
        type: integer
        example: 30
      count:
        type: integer
        example: 10
      per_page:
        type: integer
        example: 10
      current_page:
        type: integer
        example: 2
      total_pages:
        type: integer
        example: 3
      links:
        type: object
        properties:
          first:
            type: string
          previous:
            type: string
          next:
            type: string
          last:
            type: string
