properties:
  id:
    type: string
    example: builder-2b66bb79
    readOnly: true
  reseller_id:
    type: integer
    required: false
    readonly: false
    example: 12345
  employee_id:
    type: integer
    required: false
    readonly: false
    example: 54321
  locked:
    type: boolean
    required: false
    example: false
    readOnly: false
description: 'Builder Configuration'
