properties:
  id:
    type: string
    example: builder-2b66bb79
    readOnly: true
  reseller_id:
    type: integer
    required: false
    readonly: false
    example: 12345
  employee_id:
    type: integer
    required: false
    readonly: false
    example: 54321
  deploy_on:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    required: false
description: 'Builder Configuration'
