### Create Availability Zone in hidden region
GET https://{{host}}/{{version}}/availability-zones/az-7c32168a-dev
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "200 Response not received");
});

client.global.set('availability_zone_id', response.body.data.id);
client.log('Availability Zone ID: ' + response.body.data.id);
%}

### Get availability zone collection
GET https://{{host}}/{{version}}/availability-zones
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%
client.test('Hidden Region AZ not present', function () {
    var records = response.body.data;
    for (k=0; k < records.length; k++) {
        if (records[k].id === client.global.get('availability_zone_id')) {

        }
        client.assert(
                records[k].id !== client.global.get('availability_zone_id'),
                'Hidden AZ found in collection'
        );
    }
});
%}
