GET https://{{host}}/{{version}}/availability-zones/{{dev_availability_zone_id}}/host-specs
X-consumer-custom-id:  1-1
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###