properties:
  id:
    type: string
    example: is-2b66bb79
    readOnly: true
  name:
    type: string
    required: false
    example: 'Mcafee'
    readOnly: false
  instance_id:
    type: string
    required: true
    description : The ID of the instance that the software is associated with
    example: i-4c63cf58
    readOnly: false
  software_id:
    type: string
    required: true
    description : The ID of the software that the instance is associated with
    example: soft-4c63cf58
    readOnly: false
  sync :
    type : object
    readOnly : true
    properties :
      status :
        description : "The status of the most recent sync performed on the resource. Possible values: in-progress, failed, complete."
        example : complete
      type :
        description : "The type of the most recent sync performed on the resource. Possible values: update / delete."
        example : update
  created_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
  updated_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
description: 'Instance Software'
