properties:
  id:
    type: string
    example: hg-2b66bb79
    readOnly: true
  name:
    type: string
    required: false
    example: 'Host Group 1'
    readOnly: false
  vpc_id :
    type : string
    example : vpc-4c63cf58
    readOnly : false
  availability_zone_id:
    type: string
    required: false
    example: 'az-2b66bb79'
    readOnly : false
  host_spec_id:
    type: string
    required: true
    description : The host spec to use with this host group
    example: hs-4c63cf58
    readOnly: false
  windows_enabled:
    type: bolean
    required: false
    description : Determines whether the host group contains windows-enabled hosts, defaults to false.
    example: true
    readOnly: false
  task:
    type: object
    readOnly: true
    properties:
      status:
        description: "The status of the most recent task performed on the resource. Possible values: in-progress, failed, complete."
        example: complete
      name:
        description: "The name of the most recent task performed on the resource."
        example: update
  created_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
  updated_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
description: 'Host Groups'
