POST https://{{host}}/{{version}}/host-specs
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
    "name": "Test host spec",
    "cpu_sockets": 2,
    "cpu_type": "E5-2643 v3",
    "cpu_cores": 6,
    "cpu_clock_speed": 4000,
    "ram_capacity": 64,
    "availability_zones": [
        {
            "id": "az-aaaaaaaa"
        },
        {
            "id": "az-00488c3b"
        }
    ]
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 200");
});

client.global.set('hostSpecId', response.body.data.id);
client.log('hostSpecId: ' + response.body.data.id);
%}

###

###
GET https://{{host}}/{{version}}/host-specs
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 1-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET https://{{host}}/{{version}}/host-specs/{{hostSpecId}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###

PATCH https://{{host}}/{{version}}/host-specs/{{hostSpecId}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 1-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
    "name": "Test host spec - RENAMED",
    "cpu_sockets": 3,
    "cpu_type": "E5-2643 v3 - RENAMED",
    "cpu_cores": 7,
    "cpu_clock_speed": 5000,
    "ram_capacity": 128,
    "availability_zones": [
        {
            "id": "az-aaaaaaaa"
        }
    ]
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###

GET https://{{host}}/{{version}}/host-specs/{{hostSpecId}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.data.name === "Test host spec - RENAMED", "name property incorrect");
  client.assert(response.body.data.cpu_sockets === 3, "cpu_sockets property incorrect");
  client.assert(response.body.data.cpu_type === "E5-2643 v3 - RENAMED", "cpu_type property incorrect");
  client.assert(response.body.data.cpu_cores === 7, "cpu_cores property incorrect");
  client.assert(response.body.data.cpu_clock_speed === 5000, "cpu_clock_speed property incorrect");
  client.assert(response.body.data.ram_capacity === 128, "ram_capacity property incorrect");
});
%}
###

###
DELETE https://{{host}}/{{version}}/host-specs/{{hostSpecId}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}
###

GET https://{{host}}/{{version}}/host-specs/{{hostSpecId}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 404, "Response status is not 404");
});
%}
###

GET https://{{host}}/{{version}}/availability-zones/az-aaaaaaaa/host-specs
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 404, "Response status is not 404");
});
%}
###