### Get Volume Group Collection
GET https://{{host}}/{{version}}/volume-groups?sort=created_at:desc
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test('Get Volume Group Item', function () {
    client.assert(response.status === 200, '200 response not received');
});
client.global.set('volume_group_id', response.body.data[0].id);
%}

### Get Volume Group Resource
GET https://{{host}}/{{version}}/volume-groups/{{volume_group_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test('Get Volume Group Item', function () {
    client.assert(response.status === 200, '200 response not received');
});
%}