properties:
  id:
    type: string
    example: soft-2b66bb79
    readOnly: true
  name:
    type: string
    required: false
    example: 'Mcafee'
    readOnly: false
  platform:
    type: string
    required: true
    readOnly: false
    example: 'Linux'
description: 'Software'
