properties:
  id:
    type: string
    example: 'lb-2b66bb79'
    readOnly: true
  name:
    type: string
    required: false
    example: 'Load Balancer 1'
  availability_zone_id:
    type: string
    required: true
    example: 'az-2b66bb79'
    readOnly : false
  vpc_id:
    type: string
    required: true
    example: 'vpc-2b66bb79'
  load_balancer_spec_id:
    description: "Load balancer specification used by the service."
    type: string
    required: true
    example: 'lbs-2b66bb79'
    readOnly : false
  network_id:
    description: "Network to assign to the load balancer service"
    required: true
    writeOnly: true
    type: string
    example: net-abc123
  sync:
    type: object
    readOnly: true
    properties:
      status:
        description: "The status of the most recent sync performed on the resource. Possible values: in-progress, failed, complete."
        example: complete
      type:
        description: "The type of the most recent sync performed on the resource. Possible values: update / delete."
        example: update
  config_id:
    description: Load balancer cluster config ID
    type: string
    readOnly: true
    example: 123
  nodes:
    type: integer
    required: false
    readOnly: true
    description: "Number of nodes the load balancer has"
    example: 2
  created_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
  updated_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
description: 'Load Balancers'
