

GET https://api.ukfast.io/ecloud/v2/regions/reg-b49ar89h/prices
Accept: */*
Cache-Control: no-cache
Authorization: s2qjbSeqbAfhSmVIivSn7ytBLsBBd0lc
Content-Type:  application/json

<> 2020-12-10T145343.200.json
<> 2020-12-10T145332.200.json
