POST https://{{host}}/{{version}}/ip-addresses
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: {{dev_reseller_id_admin}}
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
    "name": "Test",
    "ip_address": "1.1.1.1",
    "network_id": "{{dev_network_id}}",
    "type": "cluster"
}

> {%
client.test('Create', function () {
    client.assert(response.status === 201, '201 response not received');
});
client.global.set('ip_address_id', response.body.data.id);
client.log('IP Address ID: ' + response.body.data.id);
%}

###
GET https://{{host}}/{{version}}/ip-addresses?sort=ip_address:desc
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: {{dev_reseller_id_admin}}
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test('Get Collection', function () {
    client.assert(response.status === 200, '200 response not received');
});
%}

###
GET https://{{host}}/{{version}}/ip-addresses/{{ip_address_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: {{dev_reseller_id_admin}}
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test('Get Item', function () {
    client.assert(response.status === 200, '200 response not received');
    client.assert(response.body.data.id === client.global.get('ip_address_id'), 'Invalid ID');
    client.assert(response.body.data.ip_address === '1.1.1.1', 'Invalid ip_address');
    client.assert(response.body.data.network_id === 'net-aaaaaaaa', 'Invalid network_id');
    client.assert(response.body.data.type === 'cluster', 'Invalid type');
});
%}

### For the next 2 tests, pick a random nic id from the nics table (deploy an instance if there are none) and add into the pivot table ip_address_nic with the ip_address_id to test this

### 1. ip-addresses/{ipAddressId}/nics
GET https://{{host}}/{{version}}/ip-addresses/{{ip_address_id}}/nics
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: {{dev_reseller_id_admin}}
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

### 2. nics/{id}/ip-addresses
GET https://{{host}}/{{version}}/nics/nic-40f1be93-dev/ip-addresses
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: {{dev_reseller_id_admin}}
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

###
PATCH https://{{host}}/{{version}}/ip-addresses/{{ip_address_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: {{dev_reseller_id_admin}}
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
    "name": "Test - Renamed",
    "ip_address": "2.2.2.2",
    "type": "normal"
}

> {%
client.test('Update Volume Group', function () {
    client.assert(response.status === 200, '200 response not received');
});
%}

###
GET https://{{host}}/{{version}}/ip-addresses/{{ip_address_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: {{dev_reseller_id_admin}}
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test('Get Item', function () {
    client.assert(response.status === 200, '200 response not received');
    client.assert(response.body.data.name === 'Test - Renamed', 'Name was not updated');
    client.assert(response.body.data.ip_address === '2.2.2.2', 'ip_address was not updated');
    client.assert(response.body.data.type === 'dhcp', 'type was not updated');
});
%}

### (Note: delete any records from the ip_address_nic table first or will fail validation)
DELETE https://{{host}}/{{version}}/ip-addresses/{{ip_address_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: {{dev_reseller_id_admin}}
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

> {%
client.test('Delete Item', function () {
    client.assert(response.status === 204, '204 response not received');
});
%}



