GET https://{{host}}/{{version}}/firewall-policies/fwp-aaaaaaaa/firewall-rules
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.data[0].firewall_policy_id === "fwp-aaaaaaaa", "Incorrect firewall policy id");
});
%}