### Create VIP
POST https://kong.staging.rnd.ukfast/loadbalancers/v2/clusters/5208/vips
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json

{
    "internal_cidr": "192.168.1.6/24"
}



### Get VIPs
GET https://kong.staging.rnd.ukfast/loadbalancers/v2/vips
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json

<> 2021-11-10T141220.200.json

### Delete VIP
DELETE https://kong.staging.rnd.ukfast/loadbalancers/v2/vips/13980
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json

### ACLs
GET https://kong.staging.rnd.ukfast/loadbalancers/v2/acls/7267
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json
