# See: https://gitlab.devops.ukfast.co.uk/ukfast/api.ukfast/monitoring/-/blob/master/openapi.yaml

## devices

### Get devices collection
GET https://kong.staging.rnd.ukfast/monitoring/v1/devices
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json

### Get device item
GET https://kong.staging.rnd.ukfast/monitoring/v1/devices/135e06d1-fa77-4f3b-8e68-f2a2b032ca04
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json



### Create device
POST https://kong.staging.rnd.ukfast/monitoring/v1/devices
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json

{

}
###

# accounts

### Get account
GET https://kong.staging.rnd.ukfast/monitoring/v1/account
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json
X-Reseller-Id: 1

### Account not found
GET https://kong.staging.rnd.ukfast/monitoring/v1/account
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json
X-Reseller-Id: 100

###
POST https://kong.staging.rnd.ukfast/monitoring/v1/account
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json
X-Reseller-Id: 10

{
    "name": "banana 2"
}
###

# collectors

### Get collection
GET https://kong.staging.rnd.ukfast/monitoring/v1/collectors
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json

### Get collection - filtered
GET https://kong.staging.rnd.ukfast/monitoring/v1/collectors?is_shared=true&datacentre_id=8
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json
