# See: https://gitlab.devops.ukfast.co.uk/ukfast/api.ukfast/monitoring/-/blob/master/openapi.yaml

## devices

### Get devices collection
GET https://kong.staging.rnd.ukfast/monitoring/v1/devices
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json

### Get device item
GET https://kong.staging.rnd.ukfast/monitoring/v1/devices/135e06d1-fa77-4f3b-8e68-f2a2b032ca04
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json



### Create device
POST https://kong.staging.rnd.ukfast/monitoring/v1/devices
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json

{
    "reference_type": "server",
    "reference_id": "i-10d78ef4-dev",
    "collector_id": "254fa2d8-e63a-4535-a892-f31290e3b94e",
    "display_name": "Test",
    "tier_id": "8485a243-8a83-11ec-915e-005056ad1662",
    "account_id": "80cd084c-f17a-4c57-b03e-15ff0058762d",
    "ip_address": "46.37.163.93",
    "snmp_community": "public",
    "platform": "Linux",
    "username": "lm.i-10d78ef4-dev",
    "password": "twe2Wjc90obkYpN4fp3onmAze"
}
###

DELETE https://kong.staging.rnd.ukfast/monitoring/v1/devices/7799334a-ec7f-443e-b853-491a4da2d428
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json



# accounts

### Get account
GET https://kong.staging.rnd.ukfast/monitoring/v1/accounts
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json
X-Reseller-Id: 1

### Account not found
GET https://kong.staging.rnd.ukfast/monitoring/v1/accounts/qwerty
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json
X-Reseller-Id: 100

###
POST https://kong.staging.rnd.ukfast/monitoring/v1/accounts
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json
X-Reseller-Id: 10

{
    "name": "banana 2"
}
###

# collectors

### Get collection
GET https://kong.staging.rnd.ukfast/monitoring/v1/collectors
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json

### Get collection - filtered
GET https://kong.staging.rnd.ukfast/monitoring/v1/collectors?is_shared=true&datacentre_id=8
Accept: */*
Cache-Control: no-cache
Authorization: myukfast
Content-Type:  application/json
