properties:
  id:
    type: string
    example: img-2b66bb79
    readOnly: true
  name:
    type: string
    example: 'CentOS 7'
    readOnly: true
  logo_uri:
    type: string
    example: 'https://example.com/image.png'
    readOnly: true
  documentation_uri:
    type: string
    example: 'https://example.com/docs'
    readOnly: true
  vpc_id:
    type: string
    description: ID of the VPC that the image is assigned to for private images
    example: 'vpc-abc123'
    readOnly: true
  description:
    type: string
    example: 'Linux operating system'
    readOnly: true
description: 'Images'
