properties:
  id:
    type: string
    example: imgparam-abc123xyz
    readOnly: true
  image_id:
    type: string
    example: img-2b66bb79
    readOnly: true
  key:
    type: string
    example: 'ukfast.spec.ram.min'
    readOnly: true
  value:
    type: string
    example: '1024'
    readOnly: true
description: 'Image Parameters'
