## Setup Dependancies
POST https://{{host}}/{{version}}/regions
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
    "name": "Test Region - LbcCrud"
}

> {%
client.global.set('region_id', response.body.data.id);
client.log('Region ID: ' + response.body.data.id);
%}

###
POST https://{{host}}/{{version}}/load-balancer-specs
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
    "name": "small-1",
    "node_count": 1,
    "cpu": 1,
    "ram": 2,
    "hdd": 20,
    "iops": 300,
    "image_id": "img-aaaaaaaa"
}

> {%
client.global.set('load_balancer_spec_id', response.body.data.id);
client.log('LBS ID: ' + response.body.data.id);
%}

###
POST https://{{host}}/{{version}}/availability-zones
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
  "code": "MAN1",
  "name": "Test AZ - LbcCrud",
  "datacentre_site_id": 111,
  "region_id": "{{region_id}}"
}

> {%
client.global.set('availability_zone_id', response.body.data.id);
client.log('Availability Zone ID: ' + response.body.data.id);
%}

###
POST https://{{host}}/{{version}}/vpcs
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json
X-Reseller-Id: 1

{
  "region_id": "{{region_id}}"
}

> {%
client.global.set('vpc_id', response.body.data.id);
client.log('VPC UUID: ' + response.body.data.id);
%}
###
## This should fail with validation error; "Resources must be in the same availability zone"

POST https://{{host}}/{{version}}/load-balancers
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
  "name": "Test",
  "availability_zone_id": "{{availability_zone_id}}",
  "vpc_id": "{{vpc_id}}",
  "load_balancer_spec_id": "{{load_balancer_spec_id}}",
  "nodes": 3,
  "network_id": "{{dev_network_id}}"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 422, "Response status is not 422");
});

client.global.set('lbc_id', response.body.data.id);
client.log('LBC ID: ' + response.body.data.id);
%}