###
POST https://{{host}}/{{version}}/vpcs
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
    "name": "TEST VPC",
    "region_id": "{{dev_region_id}}"
}

> {%
client.global.set('vpc_id', response.body.data.id);
client.log('VPC Id : ' + response.body.data.id);
%}

###
GET https://{{host}}/{{version}}/vpcs
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json
###

###
GET https://{{host}}/{{version}}/vpcs/vpc-47100759
X-consumer-custom-id:  7052-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json
###

GET https://{{host}}/{{version}}/vpcs/vpc-47100759/tasks
X-consumer-custom-id:  7052-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json
###

PATCH https://{{host}}/{{version}}/vpcs/vpc-47100759
X-consumer-custom-id:  7052-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json###

{
    "name": "updated name"
}


###
DELETE https://{{host}}/{{version}}/vpcs/{{vpc_id}}
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json
