POST https://{{host}}/{{version}}/vpcs
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
  "name": "Test VPC",
  "region_id": "{{dev_region_id}}",
  "availability_zone_id": "{{dev_availability_zone_id}}"
}

> {%
client.global.set('vpc_id', response.body.data.id);
client.log('VPC UUID: ' + response.body.data.id);
%}
###

# Add a router to the VMP so that it has active resources
POST https://{{host}}/{{version}}/routers
Accept: */*
Cache-Control: no-cache
X-consumer-custom-id: 0-0
X-consumer-groups: ecloud.read, ecloud.write
Content-Type: application/json

{
  "vpc_id": "{{vpc_id}}",
  "availability_zone_id": "{{dev_availability_zone_id}}"
}

> {%
client.global.set('router_id', response.body.data.id);
client.log('router_id: ' + response.body.data.id);
%}
###

DELETE https://{{host}}/{{version}}/vpcs/vpc-2f011a1d-dev
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 422, "Response status is not 200");
});
%}
###

DELETE https://{{host}}/{{version}}/routers/{{router_id}}
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json
###

DELETE https://{{host}}/{{version}}/vpcs/{{vpc_id}}
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 202");
});
%}