### Create a VPC
POST https://{{host}}/{{version}}/vpcs
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
    "name": "TEST VPC",
    "region_id": "{{dev_region_id}}"
}

> {%
client.test('Create a VPC', function () {
    client.assert(response.status === 202, '202 response not received');
    client.global.set('vpc_id', response.body.data.id);
    client.log('VPC ID : ' + response.body.data.id);
});
%}

### Update VPC with Different Region ID
PATCH https://{{host}}/{{version}}/vpcs/{{vpc_id}}
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
    "region_id": "vpc-abc123xyz"
}

> {%
client.test('Update VPC with Different Region ID', function () {
    client.assert(response.status === 202, '202 response not received');
});
%}

### Confirm Region ID has not been modified
GET https://{{host}}/{{version}}/vpcs/{{vpc_id}}
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%
client.test('Confirm Region ID has not been modified ', function () {
    client.assert(response.status === 200, '200 response not received');
});
%}