#
####
#POST https://{{host}}/{{version}}/regions
#X-consumer-custom-id:  0-0
#X-consumer-groups:  ecloud.read, ecloud.write
#Content-Type:  application/json
#
#{
#  "name": "Test Region - Pete"
#}
#
#> {%
#client.global.set('region_id', response.body.data.id);
#client.log('Region UUID: ' + response.body.data.id);
#%}
#
####
#POST https://{{host}}/{{version}}/availability-zones
#X-consumer-custom-id:  0-0
#X-consumer-groups:  ecloud.read, ecloud.write
#Content-Type:  application/json
#
#{
#  "code": "MAN1",
#  "name": "Test AZ - Pete",
#  "datacentre_site_id": 111,
#  "nsx_edge_cluster_id": "8bc61267-583e-4988-b5d9-16b46f7fe900",
#  "region_id": "{{region_id}}"
#}
#
#> {%
#client.global.set('availability_zone_id', response.body.data.id);
#client.log('Availability Zone UUID: ' + response.body.data.id);
#%}
#
####
#POST https://{{host}}/{{version}}/credentials
#Accept: */*
#Cache-Control: no-cache
#X-consumer-custom-id: 0-0
#X-consumer-groups: ecloud.read, ecloud.write
#Content-Type: application/json
#
#{
#  "name": "NSX",
#  "resource_id": "{{availability_zone_id}}",
#  "host": "https://185.197.63.88",
#  "username": "ecloud.api@ecloudgov.dev",
#  "password": "a5hfysIVpUND"
#}
#
#> {%
#client.test("Request executed successfully", function() {
#  client.assert(response.status === 201, "Response status is not 200");
#});
#
#client.global.set('nsx_credential_id', response.body.data.id);
#client.log('NSX Credential ID: ' + response.body.data.id);
#%}
#
####
#
#POST https://{{host}}/{{version}}/credentials
#Accept: */*
#Cache-Control: no-cache
#X-consumer-custom-id: 0-0
#X-consumer-groups: ecloud.read, ecloud.write
#Content-Type: application/json
#
#{
#  "name": "Kingpin (G0)",
#  "resource_id": "{{availability_zone_id}}",
#  "host": "https://mgmt-20.ecloud-service.ukfast.co.uk",
#  "username": "kingpinapi",
#  "password": "tKm?c7?Ov!of",
#  "port": 8443
#}
#
####
#POST https://{{host}}/{{version}}/vpcs
#X-consumer-custom-id:  1-0
#X-consumer-groups:  ecloud.read, ecloud.write
#Content-Type:  application/json
#
#{
#  "name": "Test VPC - Pete",
#  "region_id": "{{region_id}}",
#  "availability_zone_id": "{{availability_zone_id}}"
#}
#
#> {%
#client.global.set('vpc_id', response.body.data.id);
#client.log('VPC UUID: ' + response.body.data.id);
#%}
#
####
#POST https://{{host}}/{{version}}/routers
#Accept: */*
#Cache-Control: no-cache
#X-consumer-custom-id: 1-0
#X-consumer-groups: ecloud.read, ecloud.write
#Content-Type: application/json
#
#{
#  "name": "test network",
#  "vpc_id": "{{vpc_id}}",
#  "availability_zone_id": "{{availability_zone_id}}"
#}
#
#> {%
#client.global.set('router_id', response.body.data.id);
#client.log('Router ID: ' + response.body.data.id);
#%}
#
####
#POST https://{{host}}/{{version}}/networks
#Accept: */*
#Cache-Control: no-cache
#X-consumer-custom-id: 1-0
#X-consumer-groups: ecloud.read, ecloud.write
#Content-Type: application/json
#
#{
#  "name": "test network",
#  "router_id": "{{router_id}}",
#  "availability_zone_id": "{{availability_zone_id}}"
#}
#
#> {%
#client.global.set('network_id', response.body.data.id);
#client.log('Network ID: ' + response.body.data.id);
#%}
#
####

#
#POST https://{{host}}/{{version}}/floating-ips
#Accept: */*
#Cache-Control: no-cache
#X-consumer-custom-id: 1-0
#X-consumer-groups: ecloud.read, ecloud.write
#Content-Type: application/json
#
#{
#   "vpc_id": "{{vpc_id}}"
#}
#
#> {%
#client.global.set('fip_id', response.body.data.id);
#client.log('Floating IP ID: ' + response.body.data.id);
#%}


###
POST https://{{host}}/{{version}}/instances
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
  "vpc_id": "{{dev_vpc_id}}",
  "name": "Test",
  "vcpu_cores": 1,
  "ram_capacity": 1024,
  "appliance_id": "6e12d729-ca82-49f9-89d2-eec2360c482a",
  "requires_floating_ip": true,
  "network_id": "{{dev_network_id}}",
  "volume_capacity": 30
}

> {%
client.global.set('instance_id', response.body.data.id);
client.log('Instance ID: ' + response.body.data.id);

client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201 Created");
});
%}
###

## Deploy - default network
POST https://{{host}}/{{version}}/instances
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
  "vpc_id": "vpc-c05db056",
  "vcpu_cores": 1,
  "ram_capacity": 1024,
  "appliance_id": "6e12d729-ca82-49f9-89d2-eec2360c482a",
  "requires_floating_ip": true,
  "volume_capacity": 30
}

> {%
client.global.set('instance_id', response.body.data.id);
client.log('Instance ID: ' + response.body.data.id);

client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201 Created");
});
%}
###
#

#DELETE https://{{host}}/{{version}}/instances/{{instance_id}}
#X-consumer-custom-id:  0-0
#X-consumer-groups:  ecloud.read, ecloud.write
#Content-Type:  application/json
