POST https://{{host}}/{{version}}/instances
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
  "name": "Test Locking",
  "vpc_id": "{{dev_vpc_id}}",
  "availability_zone_id": "{{dev_availability_zone_id}}",
  "image_id": "img-c879f613",
  "vcpu_cores": 1,
  "ram_capacity": 1024,
  "locked": true,
  "network_id": "net-136c72bf"
}

> {%
client.global.set("instance_id", response.body.data.id);
client.log("Instance ID: " + response.body.data.id);

client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 202");
});
%}

###
# i-60548c0b

GET https://{{host}}/{{version}}/instances/{{instance_id}}
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%

client.test("Request executed successfully", function() {
  client.assert(response.body.data.locked === true, "Resource is not lockedD");
});
%}

###

PUT https://{{host}}/{{version}}/instances/{{instance_id}}/unlock
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json
###


PATCH https://{{host}}/{{version}}/instances/{{instance_id}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json
X-Reseller-Id: 1

{
    "vcpu_cores": 2
}

> {%

client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Unlocked resource was not editable");
});
%}
###

GET https://{{host}}/{{version}}/instances/{{instance_id}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%

client.test("Request executed successfully", function() {
  client.assert(response.body.data.locked === false, "Resource is locked");
});
%}

###

PUT https://{{host}}/{{version}}/instances/{{instance_id}}/lock
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json
###


GET https://{{host}}/{{version}}/instances/{{instance_id}}
X-consumer-custom-id:  1-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%

client.test("Request executed successfully", function() {
  client.assert(response.body.data.locked === true, "Resource is not locked");
});
%}

###

PATCH https://{{host}}/{{version}}/instances/i-60548c0b
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json
X-Reseller-Id: 1

{
    "vcpu_cores": 2
}

> {%

client.test("Request executed successfully", function() {
  client.assert(response.status === 403, "Locked resource was editable");
});
%}

###

#DELETE https://{{host}}/{{version}}/instances/{{instance_id}}
#X-consumer-custom-id:  1-0
#X-consumer-groups:  ecloud.read, ecloud.write
#Content-Type:  application/json


