### Get an instance
GET https://{{host}}/{{version}}/instances?per_page=1&sort=created_at:desc
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%
client.global.set('instance_id', response.body.data[0].id);
client.global.set('current_state', response.body.data[0].locked);
client.global.set('new_state', !response.body.data[0].locked);
client.global.set('endpoint', (response.body.data[0].locked) ? 'unlock' : 'lock');
client.log('Instance ID: ' + response.body.data[0].id);
%}

### First try patch request
PATCH https://{{host}}/{{version}}/instances/{{instance_id}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
    "locked": {{new_state}}
}

### Get the instance and check that the locked value hasn't changed
GET https://{{host}}/{{version}}/instances/{{instance_id}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%
client.test('No change in locked state', function () {
    client.assert(response.body.locked === client.global.get('current_state'), 'Locked state has changed!');
});
%}

### No use the correct endpoint
PUT https://{{host}}/{{version}}/instances/{{instance_id}}/{{endpoint}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

### Get the instance and check that the locked value has changed
GET https://{{host}}/{{version}}/instances/{{instance_id}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%
client.test('Locked state has changed', function () {
    client.assert(response.body.locked === client.global.get('new_state'), 'Locked state has not changed!');
});
client.global.set('endpoint', (client.global.get('endpoint') === 'lock') ? 'unlock' : 'lock');
%}

### Undo the change
PUT https://{{host}}/{{version}}/instances/{{instance_id}}/{{endpoint}}
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json