GET https://{{host}}/{{version}}/instances/i-34df3a0b
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

> {%

client.test("Request executed successfully", function() {
  client.assert(response.body.data.name === "Test", "Default name was not set to ID");
});
%}

###

PATCH https://{{host}}/{{version}}/instances/i-37cab08d
X-consumer-custom-id:  0-0
X-consumer-groups:  ecloud.read, ecloud.write
Content-Type:  application/json

{
  "vcpu_cores": 5,
  "ram_capacity": 2048
}

> {%
client.global.set("instance_id", response.body.data.id);
client.log("Instance ID: " + response.body.data.id);

client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 202 Created");
});
%}
