properties:
  id:
    type: string
    example: ip-2b66bb79
    readOnly: true
  name:
    type: string
    required: false
    example: 'IP Address 1'
    readOnly: false
  ip_address:
    type: string
    required: true
    example: '1.1.1.1'
    readOnly: false
  network_id:
    type: string
    required: true
    example: 'net-abc123'
    readOnly: false
  type:
    type: string
    required: true
    example: 'cluster'
    readOnly: false
  created_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
  updated_at:
    type: string
    example: '2020-07-07T10:30:00+01:00'
    readOnly: true
description: 'IP Address'
