---

openapi: '3.0.0'
info:
  title: eCloud API
  version: '2.0.0'

servers:
  - url: https://api.ukfast.io

security:
  - api_key:
      - api_key

components:
  securitySchemes:
    api_key:
      type: apiKey
      description: API key authentication
      in: header
      name: Authorization
  schemas:
    Networks:
      properties:
        id:
          type: string
          example: net-2b66bb79
          readOnly: false
        name:
          type: string
          example: 'Manchester Network'
          readOnly: false
        created_at:
          type: string
          example: '2020-07-07T10:30:00+01:00'
          readOnly: false
        updated_at:
          type: string
          example: '2020-07-07T10:30:00+01:00'
          readOnly: false
        deleted_at:
          type: string
          example: '2020-07-07T10:30:00+01:00'
          readOnly: false
      description: 'Networks'
      required: {  }
    VirtualPrivateClouds:
      properties:
        id:
          type: string
          example: vdc-2b66bb79
          readOnly: false
        name:
          type: string
          example: 'Manchester Cloud 1'
          readOnly: false
        created_at:
          type: string
          example: '2020-07-07T10:30:00+01:00'
          readOnly: false
        updated_at:
          type: string
          example: '2020-07-07T10:30:00+01:00'
          readOnly: false
        deleted_at:
          type: string
          example: '2020-07-07T10:30:00+01:00'
          readOnly: false
      description: 'Virtual Private Clouds'
      required: {  }
paths:
  '/ecloud/v2/vpcs':
    get:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/VirtualPrivateClouds'
                  meta:
                    type: object
                    required:
                      - pagination
                    properties:
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 30
                          count:
                            type: integer
                            example: 10
                          per_page:
                            type: integer
                            example: 10
                          current_page:
                            type: integer
                            example: 2
                          total_pages:
                            type: integer
                            example: 3
                          links:
                            type: object
                            properties:
                              first:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/vpcs?page=1'
                              previous:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/vpcs?page=1'
                              next:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/vpcs?page=2'
                              last:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/vpcs?page=2'
      tags:
        - VirtualPrivateClouds
      parameters:
        -
          name: per_page
          in: query
          required: false
          schema:
            type: integer
          description: 'Number of items to display per page'
        -
          name: page
          in: query
          required: false
          schema:
            type: integer
          description: 'Page number to jump to'

    post:
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: vdc-2b66bb79
                  meta:
                    type: object
                    properties:
                      location:
                        type: string
                        example: 'https://api.ukfast.io/ecloud/v2/vpcs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VirtualPrivateClouds'
      tags:
        - VirtualPrivateClouds
      parameters: {  }
  '/ecloud/v2/vpcs/{vpcId}':
    get:
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/VirtualPrivateClouds'
                  meta:
                    type: object
      tags:
        - VirtualPrivateClouds
      parameters:
        -
          name: vpcId
          in: path
          required: true
          schema:
            type: string
          example: vdc-2b66bb79
    patch:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id: string
                      example: vdc-2b66bb79
                  meta:
                    type: object
                    properties:
                      location:
                        type: string
                        example: 'https://api.ukfast.io/ecloud/v2/vpcs/{vpcId}'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VirtualPrivateClouds'
      tags:
        - VirtualPrivateClouds
      parameters:
        -
          name: vpcId
          in: path
          required: true
          schema:
            type: string
          example: vdc-2b66bb79
    delete:
      responses:
        204:
          description: Success
      tags:
        - VirtualPrivateClouds
      parameters:
        -
          name: zoneId
          in: path
          required: true
          schema:
            type: string
          example: avz-2b66bb79
  '/ecloud/v2/networks':
    get:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Networks'
                  meta:
                    type: object
                    required:
                      - pagination
                    properties:
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 30
                          count:
                            type: integer
                            example: 10
                          per_page:
                            type: integer
                            example: 10
                          current_page:
                            type: integer
                            example: 2
                          total_pages:
                            type: integer
                            example: 3
                          links:
                            type: object
                            properties:
                              first:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/networks?page=1'
                              previous:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/networks?page=1'
                              next:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/networks?page=2'
                              last:
                                type: string
                                example: 'https://api.ukfast.io/ecloud/v2/networks?page=2'
      tags:
        - Networks
      parameters:
        -
          name: per_page
          in: query
          required: false
          schema:
            type: integer
          description: 'Number of items to display per page'
        -
          name: page
          in: query
          required: false
          schema:
            type: integer
          description: 'Page number to jump to'
    post:
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: net-2b66bb79
                  meta:
                    type: object
                    properties:
                      location:
                        type: string
                        example: 'https://api.ukfast.io/ecloud/v2/networks'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VirtualPrivateClouds'
      tags:
        - Networks
      parameters: {  }
  '/ecloud/v2/networks/{networkId}':
    get:
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/Networks'
                  meta:
                    type: object
      tags:
        - Networks
      parameters:
        -
          name: networkId
          in: path
          required: true
          schema:
            type: string
          example: net-2b66bb79
    patch:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id: string
                      example: net-2b66bb79
                  meta:
                    type: object
                    properties:
                      location:
                        type: string
                        example: 'https://api.ukfast.io/ecloud/v2/networks/{networkId}'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Networks'
      tags:
        - Networks
      parameters:
        -
          name: networkId
          in: path
          required: true
          schema:
            type: string
          example: net-2b66bb79
    delete:
      responses:
        204:
          description: Success
      tags:
        - Networks
      parameters:
        -
          name: networkId
          in: path
          required: true
          schema:
            type: string
          example: net-2b66bb79